### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaLytvynov** [tol8901/WA#3]
https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L19 имя класса не по БЭМ, нет смысла добавлдять -width к имени

**Comment by IlyaLytvynov** [comment]
Все стили нужно изначально разбивать на отдельные файлы, так получается каша

**Comment by IlyaLytvynov** [comment]
https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L3 - это в fonts.scss вынеси

**Comment by IlyaLytvynov** [comment]
https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L232 - тут + избыточный убери

**Comment by IlyaLytvynov** [comment]
https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L277 можно описать в селекторе movies { &:hover {}}

**Comment by tol8901** [comment]
> https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L19
> 
> имя класса не по БЭМ, нет смысла добавлдять -width к имени

Откорректировано

**Comment by tol8901** [comment]
> Все стили нужно изначально разбивать на отдельные файлы, так получается каша

Выполнено

**Comment by tol8901** [comment]
> https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L3
> 
> - это в fonts.scss вынеси

Вынес в отдельный файл fonts.scss

**Comment by tol8901** [comment]
> https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L232
> 
> - тут + избыточный убери

Убрал избыточный +

**Comment by tol8901** [comment]
> https://github.com/tol8901/WA/blob/67fdb74edc8f3a13c61e6ab25208e2acba15456b/src/final_project/final_project.scss#L277
> 
> можно описать в селекторе movies { &:hover {}}

Переписал указанным способом.
